apiVersion: v1
kind: Service
metadata:
  name: easy-currency
spec:
  type: LoadBalancer
  selector:
    app: easy-currency
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: easy-currency
spec:
  replicas: 1
  selector:
    matchLabels:
      app: easy-currency
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: easy-currency
    spec:
      containers:
      - name: easy-currency
        image: chrwalte/easy-currency:1.0.1
        ports:
        - containerPort: 80
